### ISSUE TITLE
Using this for managing .net Core Identity Data Annotations

### ISSUE THREAD

**Issue by gp2-gp2** [jsakamoto/Toolbelt.Blazor.LocalizedDataAnnotationsValidator#1]
Hi,

Can this be used also for localizing .net Core identity that is a part of Blazor Server project?
![image](https://user-images.githubusercontent.com/45717082/74018668-96ac0780-4996-11ea-802f-89594d09c4f7.png)
As in cshtml files we do not have  component for `<DataAnnotationsValidator />`

**Comment by jsakamoto** [comment]
@gp2-gp2 Sorry to late!

Unfortunately,  `LocalizedDataAnnotationsValidator` can't be using for managing .net Core Identity Data Annotations, because `LocalizedDataAnnotationsValidator` is built on "Blazor" infrastructure.

(.net Core identity UI is NOT built on "Blazor". It is built on simply "Razor View" or "Razor Pages", not "Blazor". "Blazor", "Razor View" and "Razor Pages" can be worked on a single same web app process, but those are different technologies.)

However, I'm working on adding `IStringLocalizer` support to [`Toolbelt.Blazor.I18nText`](https://github.com/jsakamoto/Toolbelt.Blazor.I18nText), and it has possibility that can be helpful  for localizing .net Core identity UI.
